name: Build Windows Host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Initialize Go module
        run: |
          if (!(Test-Path go.mod)) {
            go mod init mogged-remote
          }
          go mod tidy

      - name: Build executable
        run: |
          go build -ldflags="-s -w" -o host.exe host.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: host-windows
          path: host.exe
